export const Children = [
  {
    id: "1",
    name: "Ahmed",
    stud_stage: "Primary",
    address: "123 Main St, Cairo",
    age_group: "10",
    phone: "01012345678",
    email: "ahmed@example.com",
  },
  {
    id: "2",
    name: "Sara",
    stud_stage: "Primary",
    address: "456 Elm St, Alexandria",
    age_group: "8",
    phone: "01123456789",
    email: "sara@example.com",
  },
  {
    id: "3",
    name: "Mohamed",
    stud_stage: "Primary",
    address: "789 Oak St, Giza",
    age_group: "11",
    phone: "01234567890",
    email: "mohamed@example.com",
  },
  {
    id: "4",
    name: "Fatima",
    stud_stage: "Primary",
    address: "321 Maple St, Cairo",
    age_group: "9",
    phone: "01098765432",
    email: "fatima@example.com",
  },
  {
    id: "5",
    name: "Ali",
    stud_stage: "Primary",
    address: "654 Walnut St, Alexandria",
    age_group: "7",
    phone: "01187654321",
    email: "ali@example.com",
  },
  {
    id: "6",
    name: "Ahmed",
    stud_stage: "Primary",
    address: "123 Main St, Cairo",
    age_group: "10",
    phone: "01012345678",
    email: "ahmed@example.com",
  },
  {
    id: "7",
    name: "Sara",
    stud_stage: "Primary",
    address: "456 Elm St, Alexandria",
    age_group: "8",
    phone: "01123456789",
    email: "sara@example.com",
  },
  {
    id: "8",
    name: "Mohamed",
    stud_stage: "Primary",
    address: "789 Oak St, Giza",
    age_group: "11",
    phone: "01234567890",
    email: "mohamed@example.com",
  },
  {
    id: "9",
    name: "Fatima",
    stud_stage: "Primary",
    address: "321 Maple St, Cairo",
    age_group: "9",
    phone: "01098765432",
    email: "fatima@example.com",
  },
  {
    id: "10",
    name: "Ali",
    stud_stage: "Primary",
    address: "654 Walnut St, Alexandria",
    age_group: "7",
    phone: "01187654321",
    email: "ali@example.com",
  },
  {
    id: "11",
    name: "Ahmed Ali",
    stud_stage: "Primary",
    address: "123 Main St, Cairo, Egypt",
    "age-group < 12": true,
    phone: "+201234567890",
    email: "ahmed.ali@email.com",
  },
  {
    id: "12",
    name: "Sarah Ahmed",
    stud_stage: "Secondary",
    address: "456 Elm St, Alexandria, Egypt",
    "age-group < 12": false,
    phone: "+201234567891",
    email: "sarah.ahmed@email.com",
  },
  {
    id: "13",
    name: "Mohammed Hassan",
    stud_stage: "Primary",
    address: "789 Oak St, Giza, Egypt",
    "age-group < 12": true,
    phone: "+201234567892",
    email: "mohammed.hassan@email.com",
  },
  {
    id: "14",
    name: "John Smith",
    stud_stage: "Secondary",
    address: "123 Main St, Anytown, USA",
    age_group: "< 12",
    phone: "555-1234",
    email: "jsmith@email.com",
  },
  {
    id: "15",
    name: "Mary Johnson",
    stud_stage: "Primary",
    address: "456 Park Ave, Anytown, USA",
    age_group: "< 12",
    phone: "555-5678",
    email: "mjohnson@email.com",
  },
  {
    id: "16",
    name: "David Lee",
    stud_stage: "Secondary",
    address: "789 Elm St, Anytown, USA",
    age_group: "12-18",
    phone: "555-9012",
    email: "dlee@email.com",
  },
  {
    id: "17",
    name: "Sarah Brown",
    stud_stage: "Primary",
    address: "321 Oak St, Anytown, USA",
    age_group: "< 12",
    phone: "555-3456",
    email: "sbrown@email.com",
  },
  {
    id: "18",
    name: "Tom Wilson",
    stud_stage: "Secondary",
    address: "654 Maple Ave, Anytown, USA",
    age_group: "12-18",
    phone: "555-7890",
    email: "twilson@email.com",
  },
  {
    id: "19",
    name: "Emily Davis",
    stud_stage: "Primary",
    address: "987 Pine St, Anytown, USA",
    age_group: "< 12",
    phone: "555-2345",
    email: "edavis@email.com",
  },
  {
    id: "20",
    name: "James Johnson",
    stud_stage: "Secondary",
    address: "246 Cedar St, Anytown, USA",
    age_group: "12-18",
    phone: "555-6789",
    email: "jjohnson@email.com",
  },
  {
    id: "21",
    name: "Linda Brown",
    stud_stage: "Primary",
    address: "369 Elm St, Anytown, USA",
    age_group: "< 12",
    phone: "555-1234",
    email: "lbrown@email.com",
  },
  {
    id: "22",
    name: "Mark Davis",
    stud_stage: "Secondary",
    address: "582 Maple Ave, Anytown, USA",
    age_group: "12-18",
    phone: "555-5678",
    email: "mdavis@email.com",
  },
  {
    id: "23",
    name: "Karen Wilson",
    stud_stage: "Primary",
    address: "795 Oak St, Anytown, USA",
    age_group: "< 12",
    phone: "555-9012",
    email: "kwilson@email.com",
  },
  {
    id: "24",
    name: "Chris Lee",
    stud_stage: "Secondary",
    address: "123 Main St, Anytown, USA",
    age_group: "12-18",
    phone: "555-3456",
    email: "clee@email.com",
  },
  {
    id: "25",
    name: "Ali",
    stud_stage: "Primary",
    address: "789 Oak St, Giza, Egypt",
    age_group: "< 12",
    phone: "+201234567892",
    email: "ali@example.com",
  },
  {
    id: "26",
    name: "Fatima",
    stud_stage: "Secondary",
    address: "321 Pine St, Cairo, Egypt",
    age_group: "> 12",
    phone: "+201234567893",
    email: "fatima@example.com",
  },
  {
    id: "27",
    name: "Omar",
    stud_stage: "Primary",
    address: "654 Maple St, Alexandria, Egypt",
    age_group: "< 12",
    phone: "+201234567894",
    email: "omar@example.com",
  },
  {
    id: "28",
    name: "Nour",
    stud_stage: "Secondary",
    address: "987 Cedar St, Giza, Egypt",
    age_group: "> 12",
    phone: "+201234567895",
    email: "nour@example.com",
  },
  {
    id: "29",
    name: "Khaled",
    stud_stage: "Primary",
    address: "246 Walnut St, Cairo, Egypt",
    age_group: "< 12",
    phone: "+201234567896",
    email: "khaled@example.com",
  },
  {
    id: "30",
    name: "Laila",
    stud_stage: "Secondary",
    address: "135 Birch St, Alexandria, Egypt",
    age_group: "> 12",
    phone: "+201234567897",
    email: "laila@example.com",
  },
  {
    id: "31",
    name: "Youssef",
    stud_stage: "Primary",
    address: "864 Oak St, Giza, Egypt",
    age_group: "< 12",
    phone: "+201234567898",
    email: "youssef@example.com",
  },
  {
    id: "32",
    name: "Aya",
    stud_stage: "Secondary",
    address: "753 Pine St, Cairo, Egypt",
    age_group: "> 12",
    phone: "+201234567899",
    email: "aya@example.com",
  },
];
